package_assets: always
compress_assets: off
template_function: _.template
javascripts:
  app:
    - app/assets/javascripts/jquery.min.js
    - app/assets/javascripts/json2.js
    - app/assets/javascripts/underscore.js
    - app/assets/javascripts/backbone.js
    - app/assets/javascripts/jquery.dotimeout.js
    - app/assets/javascripts/application.js
    - app/assets/javascripts/button.js
    - app/assets/javascripts/utils.js
    - app/assets/javascripts/main.js
    - app/assets/javascripts/jquery.cookie.js
    - app/assets/javascripts/events.js
    - app/assets/javascripts/models/*.js
    - app/assets/javascripts/views/*.js
    - app/assets/javascripts/templates/*.jst

  sdk:
    - app/assets/javascripts/json2.js
    - app/assets/javascripts/jquery.min.js
    - app/assets/javascripts/embed_button.js

  embedded_button:
    - app/assets/javascripts/json2.js
    - app/assets/javascripts/jquery.min.js
    - app/assets/javascripts/jquery.cookie.js
    - app/assets/javascripts/underscore.js
    - app/assets/javascripts/backbone.js
    - app/assets/javascripts/templates/one_that.html.jst
    - app/assets/javascripts/models/fucker.js
    - app/assets/javascripts/show_button.js
    - app/assets/javascripts/facebook.js
    - app/assets/javascripts/data.js

stylesheets:
  all:
    - app/assets/stylesheets/button.css
    - app/assets/stylesheets/main.css
    - app/assets/stylesheets/main_body.css

  embedded_button:
    - app/assets/stylesheets/button.css
    - app/assets/stylesheets/main.css
    - app/assets/stylesheets/embedded_button.css
