package_assets: always
compress_assets: off
template_function: _.template
javascripts:
  app:
    - app/assets/javascripts/jquery.min.js
    - app/assets/javascripts/json2.js
    - app/assets/javascripts/underscore.js
    - app/assets/javascripts/backbone.js
    - app/assets/javascripts/jquery.dotimeout.js
    - app/assets/javascripts/application.js
    - app/assets/javascripts/button.js
    - app/assets/javascripts/utils.js
    - app/assets/javascripts/main.js
    - app/assets/javascripts/jquery.cookie.js
    - app/assets/javascripts/models/*.js
    - app/assets/javascripts/views/*.js
    - app/assets/javascripts/templates/*.jst

  access_token:
    - app/assets/javascripts/jquery.min.js
    - app/assets/javascripts/access_token_script.js

stylesheets:
  all:
    - app/assets/stylesheets/button.css
    - app/assets/stylesheets/main.css
